# 使用env来支持docker化编写配置

from os import environ as env

DATABASE_BASENAME = env["DATABASE_BASENAME"]
DATABASE_ADDRESS = env["DATABASE_ADDRESS"]
DATABASE_USER = env["DATABASE_USER"]
DATABASE_PASSWORD = env["DATABASE_PASSWORD"]

# DATABASE_ADDRESS = env["DATABASE_ADDRESS"]
# DATABASE_ADDRESS = env["DATABASE_ADDRESS"]